version: '3'
services:
  site:
    build:
      context: "."
      dockerfile: "Dockerfile-site-dev"
    volumes:
      - "./site/:/usr/share/nginx/html"
    ports:
      - "8080:80"
  app:
    build:
      context: "."
      dockerfile: "Dockerfile-server-dev"
    volumes:
      - "./app/:/app/"
    ports:
     - "3000:3000"
     - "9229:9229"
